# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import katanemo_sdk
from katanemo_sdk.paths.org_account_id_sso_connections_saml_connection_id_login_trigger import get  # noqa: E501
from katanemo_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestOrgAccountIdSsoConnectionsSamlConnectionIdLoginTrigger(ApiTestMixin, unittest.TestCase):
    """
    OrgAccountIdSsoConnectionsSamlConnectionIdLoginTrigger unit test stubs
        Triggers SAML SSO  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = get.ApiForget(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 0




if __name__ == '__main__':
    unittest.main()
