# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from katanemo_sdk import schemas  # noqa: F401


class OIDCPublicKey(
    schemas.AnyTypeSchema,
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            kid = schemas.StrSchema
            alg = schemas.StrSchema
            e = schemas.StrSchema
            n = schemas.StrSchema
            use = schemas.StrSchema
            kty = schemas.StrSchema
            __annotations__ = {
                "kid": kid,
                "alg": alg,
                "e": e,
                "n": n,
                "use": use,
                "kty": kty,
            }

    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kid"]) -> MetaOapg.properties.kid: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["alg"]) -> MetaOapg.properties.alg: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["e"]) -> MetaOapg.properties.e: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["n"]) -> MetaOapg.properties.n: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["use"]) -> MetaOapg.properties.use: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["kty"]) -> MetaOapg.properties.kty: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["kid", "alg", "e", "n", "use", "kty", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kid"]) -> typing.Union[MetaOapg.properties.kid, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["alg"]) -> typing.Union[MetaOapg.properties.alg, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["e"]) -> typing.Union[MetaOapg.properties.e, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["n"]) -> typing.Union[MetaOapg.properties.n, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["use"]) -> typing.Union[MetaOapg.properties.use, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["kty"]) -> typing.Union[MetaOapg.properties.kty, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["kid", "alg", "e", "n", "use", "kty", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        kid: typing.Union[MetaOapg.properties.kid, str, schemas.Unset] = schemas.unset,
        alg: typing.Union[MetaOapg.properties.alg, str, schemas.Unset] = schemas.unset,
        e: typing.Union[MetaOapg.properties.e, str, schemas.Unset] = schemas.unset,
        n: typing.Union[MetaOapg.properties.n, str, schemas.Unset] = schemas.unset,
        use: typing.Union[MetaOapg.properties.use, str, schemas.Unset] = schemas.unset,
        kty: typing.Union[MetaOapg.properties.kty, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'OIDCPublicKey':
        return super().__new__(
            cls,
            *_args,
            kid=kid,
            alg=alg,
            e=e,
            n=n,
            use=use,
            kty=kty,
            _configuration=_configuration,
            **kwargs,
        )
