# coding: utf-8

"""
    Katanemo Authorizer

    Katanemo authorizer service for AAA  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: info@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "katanemo-python-auth-sdk"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3",
    "python-dateutil",
    "pydantic >= 1.10.5, < 2",
    "aenum"
]

setup(
    name=NAME,
    version=VERSION,
    description="Katanemo Authorizer",
    author="Katanemo Labs Inc.",
    author_email="info@katanemo.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Katanemo Authorizer"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Katanemo authorizer service for AAA  # noqa: E501
    """
)
