# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import katanemo_sdk
from katanemo_sdk.api.sign_up_login_api import SignUpLoginApi  # noqa: E501
from katanemo_sdk.rest import ApiException


class TestSignUpLoginApi(unittest.TestCase):
    """SignUpLoginApi unit test stubs"""

    def setUp(self):
        self.api = katanemo_sdk.api.sign_up_login_api.SignUpLoginApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_confirm_user(self):
        """Test case for confirm_user

        Confirm User  # noqa: E501
        """
        pass

    def test_get_password_policy(self):
        """Test case for get_password_policy

        Get password policy  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Login (Password)  # noqa: E501
        """
        pass

    def test_login_init(self):
        """Test case for login_init

        Login-init (SSO vs. Password)  # noqa: E501
        """
        pass

    def test_service_signup(self):
        """Test case for service_signup

        Sign-up for Service  # noqa: E501
        """
        pass

    def test_set_password(self):
        """Test case for set_password

        Set Password  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
