# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import katanemo_sdk
from katanemo_sdk.api.sso_api import SsoApi  # noqa: E501
from katanemo_sdk.rest import ApiException


class TestSsoApi(unittest.TestCase):
    """SsoApi unit test stubs"""

    def setUp(self):
        self.api = katanemo_sdk.api.sso_api.SsoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_oidcc_onnection(self):
        """Test case for create_oidcc_onnection

        Creates OIDC connection  # noqa: E501
        """
        pass

    def test_create_saml_connection(self):
        """Test case for create_saml_connection

        Creates SAML connection  # noqa: E501
        """
        pass

    def test_create_saml_connection_mapping(self):
        """Test case for create_saml_connection_mapping

        MAP SAML Attributes  # noqa: E501
        """
        pass

    def test_delete_oidc_connection(self):
        """Test case for delete_oidc_connection

        Delete OIDC connection  # noqa: E501
        """
        pass

    def test_get_oidc_connection(self):
        """Test case for get_oidc_connection

        Get OIDC connection  # noqa: E501
        """
        pass

    def test_get_oidc_connections_for_account(self):
        """Test case for get_oidc_connections_for_account

        List OIDC Connections  # noqa: E501
        """
        pass

    def test_get_saml_connection(self):
        """Test case for get_saml_connection

        Get connection  # noqa: E501
        """
        pass

    def test_get_saml_connections_for_account(self):
        """Test case for get_saml_connections_for_account

        List SAML Connections  # noqa: E501
        """
        pass

    def test_o_idc_login_trigger(self):
        """Test case for o_idc_login_trigger

        Trigger OIDC SSO  # noqa: E501
        """
        pass

    def test_oidc_sso_call_back(self):
        """Test case for oidc_sso_call_back

        OIDC Callback  # noqa: E501
        """
        pass

    def test_s_aml_login_trigger(self):
        """Test case for s_aml_login_trigger

        Triggers SAML SSO  # noqa: E501
        """
        pass

    def test_saml_sso_call_back(self):
        """Test case for saml_sso_call_back

        SAML Callback  # noqa: E501
        """
        pass

    def test_update_oidc_connection(self):
        """Test case for update_oidc_connection

        Update OIDC connection  # noqa: E501
        """
        pass

    def test_update_saml_connection(self):
        """Test case for update_saml_connection

        Update SAML connection  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
