# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import katanemo_sdk
from katanemo_sdk.api.organization_api import OrganizationApi  # noqa: E501
from katanemo_sdk.rest import ApiException


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self):
        self.api = katanemo_sdk.api.organization_api.OrganizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_client_key(self):
        """Test case for create_client_key

        Create API Key  # noqa: E501
        """
        pass

    def test_create_role(self):
        """Test case for create_role

        Creates Role  # noqa: E501
        """
        pass

    def test_create_user_for_account(self):
        """Test case for create_user_for_account

        Invite User  # noqa: E501
        """
        pass

    def test_delete_client_key(self):
        """Test case for delete_client_key

        Delete API Key  # noqa: E501
        """
        pass

    def test_get_account_info(self):
        """Test case for get_account_info

        Get Organization  # noqa: E501
        """
        pass

    def test_get_account_organization(self):
        """Test case for get_account_organization

        List Organizations  # noqa: E501
        """
        pass

    def test_get_client_key(self):
        """Test case for get_client_key

        Get API Key  # noqa: E501
        """
        pass

    def test_get_client_key_list(self):
        """Test case for get_client_key_list

        List API Keys  # noqa: E501
        """
        pass

    def test_get_role(self):
        """Test case for get_role

        Get Role  # noqa: E501
        """
        pass

    def test_get_roles_for_account(self):
        """Test case for get_roles_for_account

        List Roles  # noqa: E501
        """
        pass

    def test_get_user(self):
        """Test case for get_user

        Get User  # noqa: E501
        """
        pass

    def test_get_users_for_account(self):
        """Test case for get_users_for_account

        List Users  # noqa: E501
        """
        pass

    def test_update_account_info(self):
        """Test case for update_account_info

        Update Organization  # noqa: E501
        """
        pass

    def test_update_role(self):
        """Test case for update_role

        Update Role  # noqa: E501
        """
        pass

    def test_update_user(self):
        """Test case for update_user

        Update user  # noqa: E501
        """
        pass

    def test_verify_account_domain(self):
        """Test case for verify_account_domain

        Verify Domain  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
