# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern [API-first] software companies.

    Public APIs of Katanemo. With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import katanemo_sdk
from katanemo_sdk.models.organization import Organization  # noqa: E501
from katanemo_sdk.rest import ApiException

class TestOrganization(unittest.TestCase):
    """Organization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Organization
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Organization`
        """
        model = katanemo_sdk.models.organization.Organization()  # noqa: E501
        if include_optional :
            return Organization(
                account_id = '', 
                name = '', 
                admin_account = '', 
                users_count = 56, 
                roles_count = 56, 
                oidc_connections_count = 56, 
                saml_connections_count = 56, 
                launched_services = [
                    ''
                    ], 
                subscribed_services = [
                    ''
                    ], 
                subscribers = [
                    ''
                    ]
            )
        else :
            return Organization(
                account_id = '',
                name = '',
                admin_account = '',
        )
        """

    def testOrganization(self):
        """Test Organization"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
