# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by: https://openapi-generator.tech
"""

from katanemo_sdk.paths.org_account_id_keys.post import CreateClientKey
from katanemo_sdk.paths.org_account_id_user.post import CreateUserForAccount
from katanemo_sdk.paths.org_account_id_key_key_id.delete import DeleteClientKey
from katanemo_sdk.paths.org_account_id_key_key_id.get import GetClientKey
from katanemo_sdk.paths.org_account_id_keys.get import GetClientKeyList
from katanemo_sdk.paths.org_account_id_user_user_id.get import GetUser
from katanemo_sdk.paths.org_account_id_user.get import GetUsersForAccount
from katanemo_sdk.paths.org_account_id_user_user_id.put import UpdateUser


class IdentityApi(
    CreateClientKey,
    CreateUserForAccount,
    DeleteClientKey,
    GetClientKey,
    GetClientKeyList,
    GetUser,
    GetUsersForAccount,
    UpdateUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
