# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by: https://openapi-generator.tech
"""

from katanemo_sdk.paths.service.post import CreateService
from katanemo_sdk.paths.service_service_id_tags.post import CreateTags
from katanemo_sdk.paths.service_service_id.delete import DeleteService
from katanemo_sdk.paths.service_3x_a.get import GetDefaultService
from katanemo_sdk.paths.service_service_id__well_known_jwks_json.get import GetDeveloperPublicKeys
from katanemo_sdk.paths.service_service_id.get import GetService
from katanemo_sdk.paths.service_service_id_tags.get import GetTagsForResource
from katanemo_sdk.paths.service.get import ListServicesByDeveloper
from katanemo_sdk.paths.service_service_id.put import UpdateService


class ServiceApi(
    CreateService,
    CreateTags,
    DeleteService,
    GetDefaultService,
    GetDeveloperPublicKeys,
    GetService,
    GetTagsForResource,
    ListServicesByDeveloper,
    UpdateService,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
