# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by: https://openapi-generator.tech
"""

from katanemo_sdk.paths.org_account_id_sso_connections_oidc.post import CreateOidccOnnection
from katanemo_sdk.paths.org_account_id_sso_connections_saml.post import CreateSamlConnection
from katanemo_sdk.paths.org_account_id_sso_connections_saml_connection_id_map_attribute_to_roles.post import CreateSamlConnectionMapping
from katanemo_sdk.paths.org_account_id_sso_connections_oidc_connection_id.delete import DeleteOidcConnection
from katanemo_sdk.paths.org_account_id_sso_connections_oidc_connection_id.get import GetOidcConnection
from katanemo_sdk.paths.org_account_id_sso_connections_oidc.get import GetOidcConnectionsForAccount
from katanemo_sdk.paths.org_account_id_sso_connections_saml_connection_id.get import GetSamlConnection
from katanemo_sdk.paths.org_account_id_sso_connections_saml.get import GetSamlConnectionsForAccount
from katanemo_sdk.paths.org_account_id_sso_connections_oidc_connection_id_login_trigger.get import OIdcLoginTrigger
from katanemo_sdk.paths.org_account_id_sso_connections_oidc_connection_id_sso_callback.get import OidcSsoCallBack
from katanemo_sdk.paths.org_account_id_sso_connections_saml_connection_id_login_trigger.get import SAmlLoginTrigger
from katanemo_sdk.paths.org_account_id_sso_connections_saml_connection_id_sso_callback_saml_acs.post import SamlSsoCallBack
from katanemo_sdk.paths.org_account_id_sso_connections_oidc_connection_id.put import UpdateOidcConnection
from katanemo_sdk.paths.org_account_id_sso_connections_saml_connection_id.put import UpdateSamlConnection


class SsoApi(
    CreateOidccOnnection,
    CreateSamlConnection,
    CreateSamlConnectionMapping,
    DeleteOidcConnection,
    GetOidcConnection,
    GetOidcConnectionsForAccount,
    GetSamlConnection,
    GetSamlConnectionsForAccount,
    OIdcLoginTrigger,
    OidcSsoCallBack,
    SAmlLoginTrigger,
    SamlSsoCallBack,
    UpdateOidcConnection,
    UpdateSamlConnection,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
