# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist

class ClientKeyObject(BaseModel):
    """
    ClientKeyObject
    """
    account_id: Optional[StrictStr] = Field(None, alias="accountId")
    roles: Optional[conlist(StrictStr)] = None
    client_name: Optional[StrictStr] = Field(None, alias="clientName")
    client_key_id: Optional[StrictStr] = Field(None, alias="clientKeyId")
    service_id: Optional[StrictStr] = Field(None, alias="serviceId")
    is_active: Optional[StrictBool] = Field(None, alias="isActive")
    __properties = ["accountId", "roles", "clientName", "clientKeyId", "serviceId", "isActive"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ClientKeyObject:
        """Create an instance of ClientKeyObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ClientKeyObject:
        """Create an instance of ClientKeyObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ClientKeyObject.parse_obj(obj)

        _obj = ClientKeyObject.parse_obj({
            "account_id": obj.get("accountId"),
            "roles": obj.get("roles"),
            "client_name": obj.get("clientName"),
            "client_key_id": obj.get("clientKeyId"),
            "service_id": obj.get("serviceId"),
            "is_active": obj.get("isActive")
        })
        return _obj

