# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern [API-first] software companies.

    Public APIs of Katanemo. With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class OAuthTokenResponse(BaseModel):
    """
    OAuthTokenResponse
    """
    access_token: Optional[StrictStr] = Field(None, alias="accessToken")
    expires_in: Optional[StrictInt] = Field(None, alias="expiresIn")
    token_type: Optional[StrictStr] = Field(None, alias="tokenType")
    __properties = ["accessToken", "expiresIn", "tokenType"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OAuthTokenResponse:
        """Create an instance of OAuthTokenResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OAuthTokenResponse:
        """Create an instance of OAuthTokenResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OAuthTokenResponse.parse_obj(obj)

        _obj = OAuthTokenResponse.parse_obj({
            "access_token": obj.get("accessToken"),
            "expires_in": obj.get("expiresIn"),
            "token_type": obj.get("tokenType")
        })
        return _obj

