# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import katanemo_sdk
from katanemo_sdk.paths.authorize import post  # noqa: E501
from katanemo_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestAuthorize(ApiTestMixin, unittest.TestCase):
    """
    Authorize unit test stubs
        Initiate the login flow by redirecting to login page  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 302
    response_body = ''




if __name__ == '__main__':
    unittest.main()
