# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AssumeRoleObj(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AssumeRoleObj - a model defined in OpenAPI

        principal_id: The principal_id of this AssumeRoleObj.
        role_id: The role_id of this AssumeRoleObj.
    """

    principal_id: str = Field(alias="principalId")
    role_id: str = Field(alias="roleId")

AssumeRoleObj.update_forward_refs()
