# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AttributeRoleMapping(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AttributeRoleMapping - a model defined in OpenAPI

        attribute: The attribute of this AttributeRoleMapping.
        value: The value of this AttributeRoleMapping.
        role_id: The role_id of this AttributeRoleMapping.
    """

    attribute: str = Field(alias="attribute")
    value: str = Field(alias="value")
    role_id: str = Field(alias="roleId")

AttributeRoleMapping.update_forward_refs()
