# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AuditLogEntry(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AuditLogEntry - a model defined in OpenAPI

        timestamp: The timestamp of this AuditLogEntry.
        account_id: The account_id of this AuditLogEntry.
        service_id: The service_id of this AuditLogEntry.
        path: The path of this AuditLogEntry.
        operation: The operation of this AuditLogEntry.
        principal: The principal of this AuditLogEntry.
        authentication_code: The authentication_code of this AuditLogEntry.
        authorization_code: The authorization_code of this AuditLogEntry.
    """

    timestamp: str = Field(alias="timestamp")
    account_id: str = Field(alias="accountId")
    service_id: str = Field(alias="serviceId")
    path: str = Field(alias="path")
    operation: str = Field(alias="operation")
    principal: str = Field(alias="principal")
    authentication_code: int = Field(alias="authenticationCode")
    authorization_code: int = Field(alias="authorizationCode")

AuditLogEntry.update_forward_refs()
