# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class AuthorizeRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    AuthorizeRequest - a model defined in OpenAPI

        client_id: The client_id of this AuthorizeRequest.
        state: The state of this AuthorizeRequest [Optional].
    """

    client_id: str = Field(alias="clientId")
    state: Optional[str] = Field(alias="state", default=None)

AuthorizeRequest.update_forward_refs()
