# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class InitArcResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InitArcResponse - a model defined in OpenAPI

        queue_url: The queue_url of this InitArcResponse [Optional].
        key_id: The key_id of this InitArcResponse [Optional].
        key_secret: The key_secret of this InitArcResponse [Optional].
        session_token: The session_token of this InitArcResponse [Optional].
        expiration: The expiration of this InitArcResponse [Optional].
    """

    queue_url: Optional[str] = Field(alias="queueUrl", default=None)
    key_id: Optional[str] = Field(alias="keyId", default=None)
    key_secret: Optional[str] = Field(alias="keySecret", default=None)
    session_token: Optional[str] = Field(alias="sessionToken", default=None)
    expiration: Optional[int] = Field(alias="expiration", default=None)

InitArcResponse.update_forward_refs()
