# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class InitialLoginResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InitialLoginResponse - a model defined in OpenAPI

        sso_enabled: The sso_enabled of this InitialLoginResponse.
        sso_redirect_url: The sso_redirect_url of this InitialLoginResponse [Optional].
    """

    sso_enabled: bool = Field(alias="ssoEnabled")
    sso_redirect_url: Optional[str] = Field(alias="ssoRedirectUrl", default=None)

InitialLoginResponse.update_forward_refs()
