# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class InternalServerErrorException(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    InternalServerErrorException - a model defined in OpenAPI

        message: The message of this InternalServerErrorException [Optional].
        error_code: The error_code of this InternalServerErrorException [Optional].
    """

    message: Optional[str] = Field(alias="message", default=None)
    error_code: Optional[str] = Field(alias="errorCode", default=None)

InternalServerErrorException.update_forward_refs()
