# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class OAuthTokenResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OAuthTokenResponse - a model defined in OpenAPI

        id_token: The id_token of this OAuthTokenResponse [Optional].
        access_token: The access_token of this OAuthTokenResponse [Optional].
        expires_in: The expires_in of this OAuthTokenResponse [Optional].
        token_type: The token_type of this OAuthTokenResponse [Optional].
    """

    id_token: Optional[str] = Field(alias="idToken", default=None)
    access_token: Optional[str] = Field(alias="accessToken", default=None)
    expires_in: Optional[int] = Field(alias="expiresIn", default=None)
    token_type: Optional[str] = Field(alias="tokenType", default=None)

OAuthTokenResponse.update_forward_refs()
