# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class OIDCObj(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OIDCObj - a model defined in OpenAPI

        oidc_config_endpoint: The oidc_config_endpoint of this OIDCObj.
        redirect_url: The redirect_url of this OIDCObj [Optional].
        name: The name of this OIDCObj [Optional].
        client_id: The client_id of this OIDCObj.
        client_secret: The client_secret of this OIDCObj.
        nonce: The nonce of this OIDCObj [Optional].
        state: The state of this OIDCObj [Optional].
        account_id: The account_id of this OIDCObj [Optional].
        service_id: The service_id of this OIDCObj [Optional].
        authorization_endpoint: The authorization_endpoint of this OIDCObj [Optional].
        token_endpoint: The token_endpoint of this OIDCObj [Optional].
        user_info_endpoint: The user_info_endpoint of this OIDCObj [Optional].
        issuer_endpoint: The issuer_endpoint of this OIDCObj [Optional].
        jwks_endpoint: The jwks_endpoint of this OIDCObj [Optional].
        connection_id: The connection_id of this OIDCObj [Optional].
    """

    oidc_config_endpoint: str = Field(alias="oidcConfigEndpoint")
    redirect_url: Optional[str] = Field(alias="redirectURL", default=None)
    name: Optional[str] = Field(alias="name", default=None)
    client_id: str = Field(alias="clientId")
    client_secret: str = Field(alias="clientSecret")
    nonce: Optional[str] = Field(alias="nonce", default=None)
    state: Optional[str] = Field(alias="state", default=None)
    account_id: Optional[str] = Field(alias="accountId", default=None)
    service_id: Optional[str] = Field(alias="serviceId", default=None)
    authorization_endpoint: Optional[str] = Field(alias="authorizationEndpoint", default=None)
    token_endpoint: Optional[str] = Field(alias="tokenEndpoint", default=None)
    user_info_endpoint: Optional[str] = Field(alias="userInfoEndpoint", default=None)
    issuer_endpoint: Optional[str] = Field(alias="issuerEndpoint", default=None)
    jwks_endpoint: Optional[str] = Field(alias="jwksEndpoint", default=None)
    connection_id: Optional[str] = Field(alias="connectionId", default=None)

OIDCObj.update_forward_refs()
