# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class OIDCPublicKey(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    OIDCPublicKey - a model defined in OpenAPI

        kid: The kid of this OIDCPublicKey [Optional].
        alg: The alg of this OIDCPublicKey [Optional].
        e: The e of this OIDCPublicKey [Optional].
        n: The n of this OIDCPublicKey [Optional].
        use: The use of this OIDCPublicKey [Optional].
        kty: The kty of this OIDCPublicKey [Optional].
    """

    kid: Optional[str] = Field(alias="kid", default=None)
    alg: Optional[str] = Field(alias="alg", default=None)
    e: Optional[str] = Field(alias="e", default=None)
    n: Optional[str] = Field(alias="n", default=None)
    use: Optional[str] = Field(alias="use", default=None)
    kty: Optional[str] = Field(alias="kty", default=None)

OIDCPublicKey.update_forward_refs()
