# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class SamlSSOCallBackRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    SamlSSOCallBackRequest - a model defined in OpenAPI

        saml_response: The saml_response of this SamlSSOCallBackRequest [Optional].
    """

    saml_response: Optional[str] = Field(alias="SAMLResponse", default=None)

SamlSSOCallBackRequest.update_forward_refs()
