# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class ServiceResponseObj(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    ServiceResponseObj - a model defined in OpenAPI

        account_id: The account_id of this ServiceResponseObj [Optional].
        service_id: The service_id of this ServiceResponseObj.
        service_name: The service_name of this ServiceResponseObj.
        description: The description of this ServiceResponseObj [Optional].
        onboard_url: The onboard_url of this ServiceResponseObj.
        redirect_url: The redirect_url of this ServiceResponseObj.
        api_spec_file_contents: The api_spec_file_contents of this ServiceResponseObj.
        apis: The apis of this ServiceResponseObj.
        auth_exclusion_paths: The auth_exclusion_paths of this ServiceResponseObj [Optional].
        version: The version of this ServiceResponseObj [Optional].
        updated_at: The updated_at of this ServiceResponseObj [Optional].
        created_at: The created_at of this ServiceResponseObj [Optional].
        display_name: The display_name of this ServiceResponseObj [Optional].
        logo_url: The logo_url of this ServiceResponseObj [Optional].
        details_image_url: The details_image_url of this ServiceResponseObj [Optional].
        terms_url: The terms_url of this ServiceResponseObj [Optional].
        privacy_url: The privacy_url of this ServiceResponseObj [Optional].
        docs_url: The docs_url of this ServiceResponseObj [Optional].
    """

    account_id: Optional[str] = Field(alias="accountId", default=None)
    service_id: str = Field(alias="serviceId")
    service_name: str = Field(alias="serviceName")
    description: Optional[str] = Field(alias="description", default=None)
    onboard_url: str = Field(alias="onboardURL")
    redirect_url: str = Field(alias="redirectUrl")
    api_spec_file_contents: str = Field(alias="apiSpecFileContents")
    apis: List[str] = Field(alias="apis")
    auth_exclusion_paths: Optional[List[str]] = Field(alias="authExclusionPaths", default=None)
    version: Optional[int] = Field(alias="version", default=None)
    updated_at: Optional[int] = Field(alias="updatedAt", default=None)
    created_at: Optional[int] = Field(alias="createdAt", default=None)
    display_name: Optional[str] = Field(alias="displayName", default=None)
    logo_url: Optional[str] = Field(alias="logoUrl", default=None)
    details_image_url: Optional[str] = Field(alias="detailsImageUrl", default=None)
    terms_url: Optional[str] = Field(alias="termsUrl", default=None)
    privacy_url: Optional[str] = Field(alias="privacyUrl", default=None)
    docs_url: Optional[str] = Field(alias="docsUrl", default=None)

ServiceResponseObj.update_forward_refs()
