# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Tags(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Tags - a model defined in OpenAPI

        service_id_path: The service_id_path of this Tags [Optional].
        service_id: The service_id of this Tags.
        name: The name of this Tags.
        resource_id: The resource_id of this Tags.
        account_id: The account_id of this Tags [Optional].
        token: The token of this Tags.
        tags: The tags of this Tags.
    """

    service_id_path: Optional[str] = Field(alias="serviceIdPath", default=None)
    service_id: str = Field(alias="serviceId")
    name: str = Field(alias="name")
    resource_id: str = Field(alias="resourceId")
    account_id: Optional[str] = Field(alias="accountId", default=None)
    token: str = Field(alias="token")
    tags: Dict[str, List[str]] = Field(alias="tags")

Tags.update_forward_refs()
