# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UserRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserRequest - a model defined in OpenAPI

        account_id: The account_id of this UserRequest.
        user_id: The user_id of this UserRequest [Optional].
        tags: The tags of this UserRequest [Optional].
        roles: The roles of this UserRequest [Optional].
    """

    account_id: str = Field(alias="accountId")
    user_id: Optional[str] = Field(alias="userId", default=None)
    tags: Optional[Dict[str, List[str]]] = Field(alias="tags", default=None)
    roles: Optional[List[str]] = Field(alias="roles", default=None)

UserRequest.update_forward_refs()
