# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class UserConfirmationResponse(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserConfirmationResponse - a model defined in OpenAPI

        session: The session of this UserConfirmationResponse.
        account_id: The account_id of this UserConfirmationResponse.
        email_address: The email_address of this UserConfirmationResponse.
        service_id: The service_id of this UserConfirmationResponse.
    """

    session: str = Field(alias="session")
    account_id: str = Field(alias="accountId")
    email_address: str = Field(alias="emailAddress")
    service_id: str = Field(alias="serviceId")

UserConfirmationResponse.update_forward_refs()
