# coding: utf-8

"""
    Katanemo Authorizer

    Katanemo authorizer service for AAA  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: info@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import katanemo_auth
from katanemo_auth.models.authorization_request import AuthorizationRequest  # noqa: E501
from katanemo_auth.rest import ApiException

class TestAuthorizationRequest(unittest.TestCase):
    """AuthorizationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AuthorizationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthorizationRequest`
        """
        model = katanemo_auth.models.authorization_request.AuthorizationRequest()  # noqa: E501
        if include_optional :
            return AuthorizationRequest(
                token = '', 
                path = '', 
                http_method = '', 
                request_body = ''
            )
        else :
            return AuthorizationRequest(
                token = '',
                path = '',
                http_method = '',
        )
        """

    def testAuthorizationRequest(self):
        """Test AuthorizationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
