# coding: utf-8

# flake8: noqa

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: support@katanemo.com
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from katanemo_sdk.api_client import ApiClient

# import Configuration
from katanemo_sdk.configuration import Configuration

# import exceptions
from katanemo_sdk.exceptions import OpenApiException
from katanemo_sdk.exceptions import ApiAttributeError
from katanemo_sdk.exceptions import ApiTypeError
from katanemo_sdk.exceptions import ApiValueError
from katanemo_sdk.exceptions import ApiKeyError
from katanemo_sdk.exceptions import ApiException
