openapi: "3.0.0"
info:
  version: 1.0.0
  title: Modernizing Medicine Patient Records
  description: Cloud service to manage patient records
  termsOfService: https://swagger.io/terms/
  contact:
    name: Katanemo Labs Inc.
    email: info@katanemo.com
    url: https://katanemo.com
servers:
  - url: http://localhost:8082
components:
  schemas:
    Patient:
      properties:
        patientId:
          type: string
          description: Patient ID
        name:
          type: string
          description: Patient name
        notes:
          type: string
          description: Doctor notes
        lastVisitDate:
          type: string
          format: date-time
          description: last visit date
    Diagnostic:
      properties:
        diagnosticId:
          type: string
          description: Diagnostic ID
        patientId:
          type: string
          description: Patient ID
        report:
          type: string
          description: diagnostic report
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
paths:
  /patient:
    post:
      summary: Creates a new patient account
      description: Creates a new patient account
      requestBody:
        description: Details of patient
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: Patient
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  "/patient/{patientId}":
    get:
      summary: Gets a patient object
      description: Gets a patient object
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: string
            pattern: ^[a-zA-Z0-9\-]{3,128}$
      responses:
        '200':
          description: Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update patient record
      description: Updates a patient object
      parameters:
        - name: patientId
          in: path
          required: true
          schema:
            type: string
            pattern: ^[a-zA-Z0-9\-]{3,128}$
      responses:
        '200':
          description: Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /diagnostic:
    post:
      summary: Creates a new diagnostic record
      description: Creates a new diagnostic record for patient
      requestBody:
        description: Details of diagnostic
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Diagnostic'
      responses:
        '200':
          description: Diagnostic
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diagnostic'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  "/diagnostic/{diagnosticId}":
    get:
      summary: Gets a diagnostic object
      description: Gets a diagnostic object
      parameters:
        - name: diagnosticId
          in: path
          required: true
          schema:
            type: string
            pattern: ^[a-zA-Z0-9\-]{3,128}$
      responses:
        '200':
          description: Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diagnostic'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update diagnostic record
      description: Updates a diagnostic object
      parameters:
        - name: diagnosticId
          in: path
          required: true
          schema:
            type: string
            pattern: ^[a-zA-Z0-9\-]{3,128}$
      responses:
        '200':
          description: Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diagnostic'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
