# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import katanemo_identity
from katanemo_identity.api.arc_api import ArcApi  # noqa: E501
from katanemo_identity.rest import ApiException


class TestArcApi(unittest.TestCase):
    """ArcApi unit test stubs"""

    def setUp(self):
        self.api = katanemo_identity.api.arc_api.ArcApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_roles_for_service(self):
        """Test case for get_roles_for_service

        Get Service Roles  # noqa: E501
        """
        pass

    def test_get_tags_for_service(self):
        """Test case for get_tags_for_service

        Get Resource Tags  # noqa: E501
        """
        pass

    def test_init_arc_client(self):
        """Test case for init_arc_client

        Initialize ARC Client  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
