# coding: utf-8

"""
    Katanemo - identity, and fine-grained authorization for modern { API-first } software companies.

    With Katanemo developers can add support for users, enterprise SSO, machine keys and fine-grained authorization in minutes.  # noqa: E501

    The version of the OpenAPI document: 0.1.1
    Contact: support@katanemo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import katanemo_identity
from katanemo_identity.api.access_logs_api import AccessLogsApi  # noqa: E501
from katanemo_identity.rest import ApiException


class TestAccessLogsApi(unittest.TestCase):
    """AccessLogsApi unit test stubs"""

    def setUp(self):
        self.api = katanemo_identity.api.access_logs_api.AccessLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_audit_logs(self):
        """Test case for get_audit_logs

        List Access logs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
